a fix for searching for Flagged for Followup
maintaina-com/imp pull request #13
Opened 2023-06-01 13:43 UTC by boekhorstb1

When searching for flagged mails in Imp, there is either an error saying "the IMAP server got an error" or no search results show up.

I found a way to repair this issue, but I am not this solves the problem at the root.

2023-06-14 11:12 UTC, ralflang requested changes

2023-06-14 11:12 UTC, ralflang commented on lib/Basic/Search.php
> +                        TODO: check weither Answer, Draft and so on also need to be set in Uppercase
typo

2023-06-19 13:06 UTC, boekhorstb1 commented
adapted typo @ralflang

2023-09-15 07:05 UTC, midahp approved these changes

2023-09-19 09:49 UTC, merged